---
name: Quarto Publish

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

permissions:
  contents: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup R
        uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2
        with:
          packages: any::knitr
            any::rmarkdown
            any::downlit
            any::xml2

      - name: Render ${{ github.ref_name }} branch
        if: github.ref != 'refs/heads/main'
        uses: quarto-dev/quarto-actions/render@8a96df13519ee81fd526f2dfca5962811136661b # v2

      - name: Render and Publish to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
